### ISSUE TITLE
maven install failed

### ISSUE THREAD

**Issue by yspyhp** [devopvoid/webrtc-java#1]
hello!
Thank you for your project. I made the following errors when compiling. I don't know C language. Please help me to have a look！
![image](https://user-images.githubusercontent.com/23613386/78866640-5c341900-7a72-11ea-8bc0-dcfbcadc138f.png)

**Comment by devopvoid** [comment]
Hi,
looks like the WebRTC sources are missing. As the first step, the cmake build should have checked out and build WebRTC.
Please provide the full build log to understand what went wrong.

Regards,
Alex

**Comment by yspyhp** [comment]
I'll try another way
Copy your webrtc-java-demo (tag v0.2.0) code into my project and introduce webrtc-java(version 0.2.0)
In the use of new ScreenCapturer (); The error information is as follows
Please help me to see how to deal with it！
![image](https://user-images.githubusercontent.com/23613386/78972488-74726980-7b40-11ea-97de-d7fbbf854043.png)

**Comment by yspyhp** [comment]
I tried to get in through the entrance DesktopSourcesPresenter, like this
![image](https://user-images.githubusercontent.com/23613386/78988767-6c2c2580-7b64-11ea-9baa-330c89cadce0.png)
But this is where the code goes wrong, Don't know what happened
![image](https://user-images.githubusercontent.com/23613386/78988798-7f3ef580-7b64-11ea-880e-5ae045eab07e.png)
An error is as follows
![image](https://user-images.githubusercontent.com/23613386/78988851-9da4f100-7b64-11ea-95e1-b1e45f69807b.png)

**Comment by devopvoid** [comment]
I have to note that screen/desktop sharing is not yet fully implemented. Same for the macOS video capture.
Should be fixed within few days.

**Comment by yspyhp** [comment]
I understand. Will a new version be released at that time

**Comment by yspyhp** [comment]
Will this project be updated in the future? Hope to integrate desktop sharing functionality!

**Comment by devopvoid** [comment]
Screen / desktop sharing has been enabled as of version 0.7.0.
