### ISSUE TITLE
can I run the demo app if I clone an older release of the repo (e.g. 0.6.0)? is there a demo app coming to support the current release (0.7.0)?

### ISSUE THREAD

**Issue by hamad-9** [devopvoid/webrtc-java#104]
can I run the demo app if I clone an older release of the repo (e.g. 0.6.0)? 

is there a demo app coming to support the current release (0.7.0)?

**Comment by hamad-9** [comment]
can I run the demo app if I clone an older release of the repo (e.g. 0.6.0)? 

is there a demo app coming to support the current release (0.7.0)?

**Comment by devopvoid** [comment]
No you cant't. [AppRTC](https://github.com/webrtc/apprtc) service has been shut down. If you want, you can host this service yourself und try the demo.

> is there a demo app coming to support the current release (0.7.0)?

Yes

**Comment by hamad-9** [comment]
ok thanks
