### ISSUE TITLE
MediaDevicesTests fail "Get frame rate failed The requested attribute was not found."

### ISSUE THREAD

**Issue by swpalmer** [devopvoid/webrtc-java#12]
**Describe the bug**
Test fails:

[INFO] Running dev.onvoid.webrtc.media.MediaDevicesTests
[ERROR] Tests run: 3, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.25 s <<< FAILURE! - in dev.onvoid.webrtc.media.MediaDevicesTests
[ERROR] dev.onvoid.webrtc.media.MediaDevicesTests.getVideoDevices  Time elapsed: 0.243 s  <<< ERROR!
java.lang.Error: MMF: Get frame rate failed The requested attribute was not found.
        at webrtc.java@0.3.0-SNAPSHOT/dev.onvoid.webrtc.media.MediaDevicesTests.getVideoDevices(MediaDevicesTests.java:46)

**To Reproduce**
1. Checkout the project (changeset 61cce4508ba595bc9d1938701730151dd02efb34)
2. set JAVA_HOME to JDK 15.0.2 (Zulu full with JavaFX)
3. mvn install  (Apache Maven 3.6.3)

**Expected behavior**
Tests pass

**Desktop (please complete the following information):**
 - OS: Windows 10 64-bit
 - Microsoft Visual Studio Community 2019 Version 16.8.4
 - JDK 15.0.2  (Zulu)
- ThinkPad P1 gen 3 laptop

**Comment by devopvoid** [comment]
This issue has been fixed with 702e58c
