### ISSUE TITLE
Support linux-aarch64

### ISSUE THREAD

**Issue by nanguantong** [devopvoid/webrtc-java#126]
**Is your feature request related to a problem? Please describe.**
Build to support linux-aarch64(arm64).

**Describe the solution you'd like**
Run webrtc-java on linux aarch64 machine.

**Describe alternatives you've considered**

**Additional context**

**Comment by devopvoid** [comment]
I cross-compiled and released both, linux arm32 and arm64 builds. But I haven't tested them.
Any feedback is appreciated.
