### ISSUE TITLE
`jni::Exception` is thrown if a specific device or capability is chosen.

### ISSUE THREAD

**Issue by vria** [devopvoid/webrtc-java#13]
Hello !

[commit 1029fe](https://github.com/devopvoid/webrtc-java/commit/1029fe4dac8f1f75b698b93688ae8b18b6b98bdb) intruduced a bug that prevents to choose a video capture device on the settings page.

**Steps to reproduce the behavior:**
1. Go to settings page
2. Specify any video capture device/capability
3. Start call
4. The application crashes

When starting a call right away everything is ok.

**Details**

The exception is thrown in the method `PeerConnectionClient::addVideo` at the line `videoSource.start();` only if 
```
videoSource.setVideoCaptureDevice(device);
videoSource.setVideoCaptureCapability(capability);
```
are executed. In other words it happens when `device` and `capability` are not null.

**Desktop:**
 - OS: Ubuntu 20.10
 - All necessary libs are installed: libasound2-dev libpulse-dev libudev-dev libv4l-dev

**Comment by devopvoid** [comment]
This has been fixed with 702e58c
