### ISSUE TITLE
Windows Demo throws arcane error

### ISSUE THREAD

**Issue by vtp1** [devopvoid/webrtc-java#14]
Windows Demo throws arcane error. I tried different streams that are accessible via web browser. Please see screenshot.
May be I am doing something wrong?
Screenshot contains everything. Ran on Windows Server 2016 with Open JDK 8.
![Capture](https://user-images.githubusercontent.com/17057165/112421719-d34ad780-8cec-11eb-8f19-e2c5a201d7b7.PNG)

**Comment by vria** [comment]
Hello, try to enter the room number without "https://appr.tc/r/". Just "3631010101"

**Comment by devopvoid** [comment]
Thanks @vria !
