### ISSUE TITLE
no main manifest attribute

### ISSUE THREAD

**Issue by meeeee12** [devopvoid/webrtc-java#17]
I have successfully compiled the project in windows using "mvn install". However when I try to run it, I receive an error:

C:\Users\User\\.m2\repository\dev\onvoid\webrtc\webrtc-java\0.3.0-SNAPSHOT>java -jar webrtc-java-0.3.0-SNAPSHOT-windows-x86_64.jar
no main manifest attribute, in webrtc-java-0.3.0-SNAPSHOT-windows-x86_64.jar

**Comment by meeeee12** [comment]
I have also tried with version 0.2.0 and I get the same error

**Comment by devopvoid** [comment]
The library itself does not have a main manifest attribute.

I suppose you want to run the demo application. To build it, you have to activate the Maven `release` profile. You can do that by running `mvn install -Prelease`. Once it finishes, you will find the self-contained demo app in your project root in the folder `webrtc-demo\webrtc-demo-javafx\target`. In that folder you run, e.g. `java -jar webrtc-javafx-demo-0.3.0-SNAPSHOT-windows-x86_64.jar`

I hope that helps to clarify things.
