### ISSUE TITLE
How to start a video call programmatically

### ISSUE THREAD

**Issue by meeeee12** [devopvoid/webrtc-java#19]
I am confused how to start a video call from code. It seems I need to call PeerConnectionService login(), but where do I get the peerConnectionService instance from?

**Comment by devopvoid** [comment]
Hi @meeeee12,
it depends on what your plans are. You want to start a video call to the [AppRTC video chat app](https://appr.tc)? For this you can examine the demo code, e.g. starting from here: https://github.com/devopvoid/webrtc-java/blob/9bf8169b2d93c694b14a1529c1968598bf0a440c/webrtc-demo/webrtc-demo-api/src/main/java/dev/onvoid/webrtc/demo/presenter/StartPresenter.java#L63

The `PeerConnectionService` is a `@Singleton` and gets injected into the constructor.

The demo code only establishes video calls to the AppRTC video chat app. The `PeerConnectionService` is part of that demo code. If you are planinng to use your own WebRTC service, you need to implement your own logic around the `RTCPeerConnection`, though the demo code can be re-used. For this, I think it's a good start to go through the basic test cases of the core Java WebRTC API [here](https://github.com/devopvoid/webrtc-java/tree/master/webrtc/src/test/java/dev/onvoid/webrtc).
