### ISSUE TITLE
Documentation for the project.

### ISSUE THREAD

**Issue by AryanGitHub** [devopvoid/webrtc-java#2]
I want to use this wrapper of webrtc in my project, but I cannot understand its structure and how to begin. 

Can you help me understand the project and its docs, if possible
And how to import it into my project. Any jar file?

**Comment by FDelporte** [comment]
As mentioned in the README, I think the easiest approach is to integrate this in a Maven project:
```
<dependency>
    <groupId>dev.onvoid.webrtc</groupId>
    <artifactId>webrtc-java</artifactId>
    <version>0.5.0</version>
</dependency>
```

**Comment by kinsleykajiva** [comment]
Hi, I have seen your work it's greater and it has given me a lot of insights to web RTC. 

So I have seen also your contributions to the  https://github.com/lectureStudio/lectureStudio project .they have been helpful.
I see that there is an implementation of WEBRTC you used the Janus media server. I have been going through it for me to see how you did for a client-side using JavaFX for desktop. 

Please I need help to understand how to do it, your implementation is veeeery very advanced and you using injects at some points so it has been hard to understand the flow, I am using Janus the same as you. Do you or can you make a sample repo or example on how to implement this with out the complex flows or libs like injections (DI) more of an imperative flow, if you wish you can use JavaFX or swing .

I have been at this or reviewing your code for a week now, and it's not just working, the SDP offer is being rejected by Janus as invalid i have tried to play around with the media hoping to Janus will accept but still nothing yet. The wiki doesn't have much to offer as much code and a lot of people seem to also need help with this judging by the issues people are posting here.

Thank you for your time.

**Comment by kinsleykajiva** [comment]
@devopvoid
