### ISSUE TITLE
Publish snapshot versions

### ISSUE THREAD

**Issue by javmarina** [devopvoid/webrtc-java#21]
**Is your feature request related to a problem? Please describe.**
For my application, I would need the changes introduced in recent commits (specially https://github.com/devopvoid/webrtc-java/commit/702e58c4810132202f47ced42870ea80adba3347). However, I have not been able to build the library on my own.

**Describe the solution you'd like**
It would be really useful to have a snapshot release with the latest changes published to the repository. That way, users would not have to wait for a new release.

**Describe alternatives you've considered**
Publishing 0.3.0 right now, but I suppose it is not finished yet.

**Comment by devopvoid** [comment]
Hi @javmarina,
there are snapshots available, but I'm not sure whether the latest snapshot has the changes you need. Please try to add the following to your projects `pom.xml`

```
<repositories>
	<repository>
		<id>oss-sonatype</id>
		<name>oss-sonatype</name>
		<url>https://oss.sonatype.org/content/repositories/snapshots/</url>
		<snapshots>
			<enabled>true</enabled>
		</snapshots>
	</repository>
</repositories>
```

You can browse the snapshots [here](https://oss.sonatype.org/#view-repositories;snapshots~browsestorage~dev/onvoid/webrtc/webrtc-java).

I try to publish version 0.3 to the Maven Central the next days.

**Comment by javmarina** [comment]
The latest commit had uncompleted runs (see https://github.com/devopvoid/webrtc-java/runs/3097167829) so I guess the changes are not present in the snapshots yet. I will wait for the 0.3 release then. Thanks!

**Comment by javmarina** [comment]
Hi Alex! Do you have an idea of when the 0.3 version will be published?

**Comment by devopvoid** [comment]
I'm working on it. The build breaks with the current state. Have to check whats wrong with the toolchain.

**Comment by devopvoid** [comment]
Now you should be able to pull the latest snapshot version. The 0.3 release will follow soon.

**Comment by javmarina** [comment]
Will try soon. Thanks!!!
