### ISSUE TITLE
[QUESTION] Will the release 0.3.0 be published to Maven Central?

### ISSUE THREAD

**Issue by rmberne** [devopvoid/webrtc-java#22]
Hi,

Thanks for release v0.3.0. Do you have plans to publish it to Maven Central?

Thanks!

**Comment by devopvoid** [comment]
The corresponding [GitHub Action](https://github.com/devopvoid/webrtc-java/actions/workflows/release.yml) was going to. But the build failed for no reason. It's really annoying. Will retry again...

**Comment by devopvoid** [comment]
@rmberne @javmarina
The version 0.3.0 has been published to the central repository ([listing](https://repo1.maven.org/maven2/dev/onvoid/webrtc/webrtc-java/0.3.0/)).
