### ISSUE TITLE
Load library 'webrtc-java' failed when use the library on my project

### ISSUE THREAD

**Issue by scott01272001** [devopvoid/webrtc-java#26]
Hi, I try to use the webrtc library which builds by myself in my project, but I get the error below, seems can not find the webrtc-java.dll on the resource, the library is built through the command "mvn install" and the version is 0.3.0, how can I fix this, thanks for your help.

![issue](https://user-images.githubusercontent.com/26453772/132631656-fb65ab0d-50aa-4916-9c5e-36da39524c1e.PNG)

**Comment by polyn0m** [comment]
@scott0127 see #23 may be useful.

**Comment by devopvoid** [comment]
See [this issue](https://youtrack.jetbrains.com/issue/IDEA-148573) if you are using IDEA.

Maybe related to your issue: 89896fd
