### ISSUE TITLE
Cannot specify camera and capabilities in Ubuntu

### ISSUE THREAD

**Issue by vria** [devopvoid/webrtc-java#30]
Hi Alex !

Thank you for [702e58c](https://github.com/devopvoid/webrtc-java/commit/702e58c4810132202f47ced42870ea80adba3347). The application does not crash anymore but I still experience [the same bug](https://github.com/devopvoid/webrtc-java/issues/13). The camera refuses to launch if `device` and `capability` are not null.

There are not much detials about this exception because it remains unhandled:
```cpp
catch (...) {
      // app falls here
      env->Throw(jni::JavaError(env, "Unhandled Exception"));
}
```

Context:
- Ubuntu 20
- variables passed to `VideoDeviceSource`
![Screenshot from 2021-09-20 13-29-20](https://user-images.githubusercontent.com/7421651/133999515-8ab9085b-8e43-4505-97db-f905311a25ef.png)

Thank you in advance.

**P.S.** This bug was introduced in [1029fe](https://github.com/devopvoid/webrtc-java/commit/1029fe4dac8f1f75b698b93688ae8b18b6b98bdb). Anterior versions work just exellent.

**Comment by devopvoid** [comment]
I'm not sure, maybe you are using the old devices API. Could you please try with:

```Java
List<VideoDevice> devices = MediaDevices.getVideoCaptureDevices();
List<VideoCaptureCapability> capabilities = MediaDevices.getVideoCaptureCapabilities(device);

VideoDevice cameraDevice = devices.get(0);  // Or any device retrieved with MediaDevices.getVideoCaptureDevices()
VideoCaptureCapability cameraCapability = capabilities.get(0);

VideoDeviceSource cameraSource = new VideoDeviceSource();
cameraSource.setVideoCaptureDevice(cameraDevice);
// Optionally
cameraSource.setVideoCaptureCapability(cameraCapability);

try {
	cameraSource.start();
}
catch (Throwable e) {
	e.printStackTrace();

	cameraSource.dispose();
}
```

**Comment by vria** [comment]
Thanks for your suggestion. This is precisely the problem. When `cameraDevice` is not null and when it is passed to `setVideoCaptureDevice` this error occurs :

```
backtrace: unhandled exception type: jni::Exception*
java.lang.Error: Unhandled Exception
	at webrtc.java/dev.onvoid.webrtc.media.video.VideoDeviceSource.start(Native Method)
```

What do you mean by "Old devices API" ? Is this related to Ubuntu libs like `udev` or `v4l2` ?

**Comment by devopvoid** [comment]
Late, but should be fixed now.
