### ISSUE TITLE
Process hang in NativeLoader "System.load()" without response

### ISSUE THREAD

**Issue by tgg9527** [devopvoid/webrtc-java#31]
hi I am trying to build the project in docker, here is my dockerfile

"""
FROM ubuntu:20.04

RUN apt-get update && apt-get install -y software-properties-common \
    && apt-get update && apt-get install -y --no-install-recommends \
       openjdk-11-jdk \
       wget \
       git \
       build-essential \
       libpulse-dev \
       libv4l-dev \
       libudev-dev \
       libasound2-dev \
    && rm -rf /var/lib/apt/lists/*
    
ARG MAVEN_VERSION=3.6.3
ARG MAVEN_HOME=/usr/share/maven

RUN wget --quiet http://ftp.mirror.tw/pub/apache/maven/maven-3/${MAVEN_VERSION}/binaries/apache-maven-${MAVEN_VERSION}-bin.tar.gz \
    && mkdir -p ${MAVEN_HOME} \
    && tar -xzf apache-maven-${MAVEN_VERSION}-bin.tar.gz -C ${MAVEN_HOME} --strip-components=1 \
    && rm -rf apache-maven-${MAVEN_VERSION}-bin.tar.gz \
    && ln -s ${MAVEN_HOME}/bin/mvn /usr/bin/mvn

ENV MAVEN_HOME ${MAVEN_HOME}
ENV MAVEN_CONFIG "$USER_HOME_DIR/.m2"

CMD ["/bin/bash"]
"""

but when running the unit test the process will hang in "NativeLoader System.load(tempPath.toAbsolutePath().toString());"  and without any response,
thank you.

**Comment by devopvoid** [comment]
See [this issue](https://youtrack.jetbrains.com/issue/IDEA-148573) if you are using IDEA.

Maybe related to your issue: 89896fd
