### ISSUE TITLE
Can't specify audio device (recording and playout)

### ISSUE THREAD

**Issue by javmarina** [devopvoid/webrtc-java#33]
**Describe the bug**
When using `AudioDeviceModule.setRecordingDevice()` or `AudioDeviceModule.setPlayoutDevice()`, the passed device is not used sometimes. Instead, the first device returned by `MediaDevices.getAudioCaptureDevices()` or `MediaDevices.getAudioRenderDevices()` is used (respectively).

**To Reproduce**

final List<AudioDevice> list = MediaDevices.getAudioCaptureDevices();
final AudioDevice audioDevice = list.get(1); // As an example

final AudioDeviceModule audioDeviceModule = new AudioDeviceModule();
audioDeviceModule.setRecordingDevice(audioDevice);

final PeerConnectionFactory factory = new PeerConnectionFactory(audioDeviceModule);
peerConnection = factory.createPeerConnection(defaultConfiguration, ...);

final AudioOptions audioOptions = new AudioOptions();
audioOptions.echoCancellation = false;
audioOptions.autoGainControl = false;
audioOptions.noiseSuppression = false;
final AudioSource audioSource = factory.createAudioSource(audioOptions);
final AudioTrack audioTrack = factory.createAudioTrack("audioTrack", audioSource);
final RTCRtpSender audioSender = peerConnection.addTrack(audioTrack, List.of("stream"));

// ... Establish connection with signaling server, etc

// Connection is established correctly (that is not the issue). But the selected device is not used. For example, if the list returns "Headphone microphone" (index 0) and "PC microphone" (index 1), the headphone is always used (you can test by blowing on it). The same happens with playout devices: the list is "Speaker" (0) and "Headphone" (1). The sound is always played through the speakers.

**Expected behavior**
The device passed to the method is used for playout/recording.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Library version: 0.3.0

**Additional context**
The [native implementation](https://github.com/devopvoid/webrtc-java/blob/master/webrtc-jni/src/main/cpp/src/JNI_AudioDeviceModule.cpp#L105) of setPlayoutDevice() iterates over the available devices and checks whether each of them corresponds to the function argument. However, if not match is found, the `index` variable will have a value of 0, and thus the fist device will be selected for playout, regardless of the function argument. This means that the issue likely lies in [this line](https://github.com/devopvoid/webrtc-java/blob/master/webrtc-jni/src/main/cpp/src/JNI_AudioDeviceModule.cpp#L128) (the if condition). It could be that the GUID is not handled consistently, or `PlayoutDeviceName()` returns -1.

This is also applicable to [setRecordingDevice()](https://github.com/devopvoid/webrtc-java/blob/master/webrtc-jni/src/main/cpp/src/JNI_AudioDeviceModule.cpp#L140), which has an identical structure.

**Comment by devopvoid** [comment]
This may be relevant here as well: https://github.com/devopvoid/webrtc-java/issues/29#issuecomment-979926225
