### ISSUE TITLE
Null pointer exception in load library of webrtc-java

### ISSUE THREAD

**Issue by RaniRaven** [devopvoid/webrtc-java#38]
For some reason the code fails upon getting NullPointerException when trying to load the webrtc-java.dll from the jar.
This is while calling the NativeClassLoader.
By the looks ]of the code, it seems like this thoing made a lot of problems before, a I cannot understand the need for all the TempPath inside.

Did anyone else tackled with this issue ?

**Comment by devopvoid** [comment]
Since the native libraries are packaged into the jar-files, they need to be extracted to the filesystem. The target directory is the temp folder.

If you haven't, create a module-info.java within your project and import (requires webrtc.java;). This should work.

**Comment by devopvoid** [comment]
See [this issue](https://youtrack.jetbrains.com/issue/IDEA-148573) if you are using IDEA.

**Comment by RaniRaven** [comment]
I have solved this issue, it seems that in IdeaJ project one needs to add the native jar as module dependency before anything will work there. Thanx.

**Comment by nanguantong** [comment]
> 

Hi, how to use the gradle jar on windows or linux without adding fmodule-info.java in IntelliJ IDEA，load error：
tmp file：
`C:\Users\ADMINI~1\AppData\Local\Temp\webrtc-java2765647831398423105.dll`

> Caused by: java.lang.RuntimeException: Load library 'webrtc-java' failed

**Comment by nanguantong** [comment]
> > 
> 
> Hi, how to use the gradle jar on windows or linux without adding fmodule-info.java in IntelliJ IDEA，load error： tmp file： `C:\Users\ADMINI~1\AppData\Local\Temp\webrtc-java2765647831398423105.dll`
> 
> > Caused by: java.lang.RuntimeException: Load library 'webrtc-java' failed

@devopvoid

**Comment by nanguantong** [comment]
And then when use maven project, it's ok to run this jar, but error happened while running `List<AudioDevice> captureDevices = MediaDevices.getAudioCaptureDevices();`
`java.lang.Error: MMF: Create device enumerator failed ÉÐδµ÷ÓÃ CoInitializ`

**Comment by nanguantong** [comment]
> > 
> 
> Hi, how to use the gradle jar on windows or linux without adding fmodule-info.java in IntelliJ IDEA，load error： tmp file： `C:\Users\ADMINI~1\AppData\Local\Temp\webrtc-java2765647831398423105.dll`
> 
> > Caused by: java.lang.RuntimeException: Load library 'webrtc-java' failed


See [](https://github.com/devopvoid/webrtc-java/issues/23)

**Comment by nanguantong** [comment]
[https://github.com/devopvoid/webrtc-java/issues/23](#23)
