### ISSUE TITLE
APM module

### ISSUE THREAD

**Issue by nanguantong** [devopvoid/webrtc-java#42]
Hi，the apm module is incompleted, I want to use the apm aec ns,  want to know how long to add this?

**Comment by devopvoid** [comment]
Hi, as far as I know AEC and NS are enabled by default, [see here](https://github.com/ibaoger/webrtc/blob/2d0e82e4cfa78787ce11e056d0449f0bd3f76bac/media/engine/webrtc_voice_engine.cc#L393).

But yes, the `AudioDeviceModule` lacks the setting of `AudioProcessing`. Maybe [this is](https://github.com/devopvoid/webrtc-java/wiki/Utility-classes#enhance-audio-quality-with-audioprocessing) of interest to you.

**Comment by devopvoid** [comment]
As of 0c51a2d you can provide your own `AudioProcessing` module to the `PeerConnectionFactory`.

Does that solve your issue?

**Comment by nanguantong** [comment]
Yeah, thanks to your advice, it's helpful, althought lack the setting of `AudioProcessing`, for example, near and far frame delay_ms and others params, hope to enhance it ~~~

**Comment by devopvoid** [comment]
What you mean, I guess, is echo cancellation, for which `set_stream_delay_ms` is required. I updated `AudioProcessing` with  `setStreamDelayMs` and `getStreamDelayMs`.
