### ISSUE TITLE
How to set video frame captuer?

### ISSUE THREAD

**Issue by SeanMooneySavari** [devopvoid/webrtc-java#54]
Is there a way to create a video track where frames are passed in via a captureFrame method?

**Comment by Charles92011** [comment]
@SeanMooneySavari You can use VideoCapture.setVideoSink and you will the onVideoFrame event.  
Once you receive the frame, I haven't figured out what to do with it. Have you worked this out? Or, are interested in collaborating on the solution?

**Comment by devopvoid** [comment]
Streaming a file is not supported yet, but will be possible in the near future. For upcoming progress see https://github.com/devopvoid/webrtc-java/issues/87
