### ISSUE TITLE
Problems using DeviceChangeListener

### ISSUE THREAD

**Issue by meeeee12** [devopvoid/webrtc-java#59]
I can listen for a device being plugged in using `DeviceChangeListener` and I can tell if it's an audio device by using instanceof ` if (device instanceof AudioDevice)` but how do I determine it it's a render or capture device?

Thanks.

**Comment by devopvoid** [comment]
As of now, you can't tell if it is a capture or render device. This can be done if you cash or retrieve the devices and compare them.

**Comment by devopvoid** [comment]
I'm closing this as it is not critical and can be accomplished by cashing the devices.
