### ISSUE TITLE
AudioDeviceModule

### ISSUE THREAD

**Issue by hussainasad6696** [devopvoid/webrtc-java#64]
### Discussed in https://github.com/devopvoid/webrtc-java/discussions/63

<div type='discussions-op-text'>

<sup>Originally posted by **hussainasad6696** May 12, 2022</sup>
Hi, my video communication is successful but for audio as per the wrapper i used AudioDeviceModule() but it started to crash the application with UnsatisfiedLinkError but then i did mvn install but that started to give error
#
# Fatal error in: ../../rtc_base/win/scoped_com_initializer.cc, line 41
# last system error: 1150
# Check failed: ((HRESULT)0x80010106L) != hr_ (-2147417850 vs. -2147417850)
# Invalid COM thread model change (MTA->STA)#
kindly help.</div>

**Comment by devopvoid** [comment]
Have you tested it with the latest version?
