### ISSUE TITLE
Share Media Resources 

### ISSUE THREAD

**Issue by kinsleykajiva** [devopvoid/webrtc-java#71]
**Is your feature request related to a problem? Please describe.**
Is there  a way to have the SDK allow the apps share resources like camera or audio. The browsers allows different tabs to do so for example test the janus video room demos https://janus.conf.meetecho.com/videoroomtest.html 

**Describe the solution you'd like**
Allow the desktop or JavaFX to also allow other apps to use the camera , because so far if I run it does not pick the resource or it throws an exception to the user in the terminal

**Comment by devopvoid** [comment]
You can share your screens or opened windows. As of version 0.7.0 its possible without known bugs. The demo code will follow soon. Thus closing this issue.
