### ISSUE TITLE
Kills The Windows Audio Drivers

### ISSUE THREAD

**Issue by kinsleykajiva** [devopvoid/webrtc-java#74]
There is a bug that I have come to realise in the library, there are times on my windows 11 x 64-bit machine, the app or java app kills the audio driver and it even makes other apps fail for example the browser won't play audio for example Youtube won't function at all.

It does not happen a lot but when it happens I have to restart my computer because there is no recovery there, like now I was watching a Youtube channel (Podcast&Chill) . I have to restart my machine to get audio hence I am here making this bug report.

Unfortunately, java doesn't throw an error for me to post or any log to show or share here. 

notes : Java17 ,JavaFX 17 .

**Comment by devopvoid** [comment]
I am not sure how this is possible. This does not relate to any Java version. Maybe an internal bug in the native WebRTC library.

What are you trying to do with this library. Do you have a minimal working example?
