### ISSUE TITLE
Generate a Mac OS arm64 release

### ISSUE THREAD

**Issue by MiguelGL-DN** [devopvoid/webrtc-java#78]
New Macs use the arm64 M1 chip from apple. Currently there are just `macos-x86_64` builds.

Do you plan to provide builds for this architecture? It would be great! 😀

If you'd need any support I'd be willing to help. Thanks!

**Comment by jason-crawford-xio** [comment]
One of my developers indicates that the x86 binary is not working on arm64 MacOS.   If this is truly the case, it would be great to have a MacOS arm64 binary.

**Comment by devopvoid** [comment]
Fixed since version 0.8.0.

**Comment by jason-crawford-xio** [comment]
Thanks Alex
