### ISSUE TITLE
How to save a video that contains sound?

### ISSUE THREAD

**Issue by ChdDongyang** [devopvoid/webrtc-java#79]
Now, I can save video and audio separately, and then use tools such as ffmpeg to process it. I want to know whether it is possible to save the video containing audio directly, instead of saving the videoframe as a picture, then synthesizing the video, and finally adding the audio track. Thank you very much!

**Comment by ChdDongyang** [comment]
Thanks your reply. I'm a beginner in the field of audio and video processing. I don't know that in the onTrack method, I can only receive video and audio separately. I will study this knowledge more deeply. Be more cautious when proposing issue in the future.

**Comment by zengchuan** [comment]
@ChdDongyang  how to save video and audio separately? I addSink but it can not .
`@Override
    public void onTrack(RTCRtpTransceiver transceiver) {
        PeerConnectionObserver.super.onTrack(transceiver);
        MediaStreamTrack mediaStreamTrack = transceiver.getReceiver().getTrack();
         if (mediaStreamTrack.getKind().equals(MediaStreamTrack.VIDEO_TRACK_KIND)) {
            VideoTrack track = (VideoTrack) mediaStreamTrack;
            track.addSink(frame -> {
                        I420Buffer i420Buffer = frame.buffer.toI420();
                        try {
                            Files.asByteSink(videoFile, FileWriteMode.APPEND).write(i420Buffer.getDataU().array());
                            Files.asByteSink(videoFile, FileWriteMode.APPEND).write(i420Buffer.getDataV().array());
                            Files.asByteSink(videoFile, FileWriteMode.APPEND).write(i420Buffer.getDataY().array());
                        } catch (Exception e) {
                            e.printStackTrace();
                        }
                        frame.retain();
                        frame.release();
                    }
            );
        } else if (mediaStreamTrack.getKind().equals(MediaStreamTrack.AUDIO_TRACK_KIND)) {
            AudioTrack track = (AudioTrack) mediaStreamTrack;
            track.addSink(new AudioTrackSink() {
                @Override
                public void onData(byte[] data, int bitsPerSample, int sampleRate, int channels, int frames) {
                    try {
                        Files.asByteSink(audioFile, FileWriteMode.APPEND).write(data);
                    } catch (Exception e) {
                        e.printStackTrace();
                    }
                }
            });
         }
    }`

**Comment by zengchuan** [comment]
@ChdDongyang how to save video and audio separately? I use addSink, but it is wrong.

@Override
    public void onTrack(RTCRtpTransceiver transceiver) {
        PeerConnectionObserver.super.onTrack(transceiver);
        MediaStreamTrack mediaStreamTrack = transceiver.getReceiver().getTrack();
         if (mediaStreamTrack.getKind().equals(MediaStreamTrack.VIDEO_TRACK_KIND)) {
            VideoTrack track = (VideoTrack) mediaStreamTrack;
            track.addSink(frame -> {
                        I420Buffer i420Buffer = frame.buffer.toI420();
                        try {
                            Files.asByteSink(videoFile, FileWriteMode.APPEND).write(i420Buffer.getDataU().array());
                            Files.asByteSink(videoFile, FileWriteMode.APPEND).write(i420Buffer.getDataV().array());
                            Files.asByteSink(videoFile, FileWriteMode.APPEND).write(i420Buffer.getDataY().array());
                        } catch (Exception e) {
                            e.printStackTrace();
                        }
                        frame.retain();
                        frame.release();
                    }
            );
         } else if (mediaStreamTrack.getKind().equals(MediaStreamTrack.AUDIO_TRACK_KIND)) {
            AudioTrack track = (AudioTrack) mediaStreamTrack;
            track.addSink(new AudioTrackSink() {
                @Override
                public void onData(byte[] data, int bitsPerSample, int sampleRate, int channels, int frames) {
                    try {
                        Files.asByteSink(audioFile, FileWriteMode.APPEND).write(data);
                    } catch (Exception e) {
                        e.printStackTrace();
                    }
                }
            });
       }
    }

**Comment by zengchuan** [comment]
@ChdDongyang how to save video and audio separately? I use addSink, but it is wrong.
`
@Override
    public void onTrack(RTCRtpTransceiver transceiver) {
        PeerConnectionObserver.super.onTrack(transceiver);
        MediaStreamTrack mediaStreamTrack = transceiver.getReceiver().getTrack();
         if (mediaStreamTrack.getKind().equals(MediaStreamTrack.VIDEO_TRACK_KIND)) {
            VideoTrack track = (VideoTrack) mediaStreamTrack;
            track.addSink(frame -> {
                        I420Buffer i420Buffer = frame.buffer.toI420();
                        try {
                            Files.asByteSink(videoFile, FileWriteMode.APPEND).write(i420Buffer.getDataU().array());
                            Files.asByteSink(videoFile, FileWriteMode.APPEND).write(i420Buffer.getDataV().array());
                            Files.asByteSink(videoFile, FileWriteMode.APPEND).write(i420Buffer.getDataY().array());
                        } catch (Exception e) {
                            e.printStackTrace();
                        }
                        frame.retain();
                        frame.release();
                    }
            );
         } else if (mediaStreamTrack.getKind().equals(MediaStreamTrack.AUDIO_TRACK_KIND)) {
            AudioTrack track = (AudioTrack) mediaStreamTrack;
            track.addSink(new AudioTrackSink() {
                @Override
                public void onData(byte[] data, int bitsPerSample, int sampleRate, int channels, int frames) {
                    try {
                        Files.asByteSink(audioFile, FileWriteMode.APPEND).write(data);
                    } catch (Exception e) {
                        e.printStackTrace();
                    }
                }
            });
       }
    }
`

**Comment by Charles92011** [comment]
@ChdDongyang check out my project: https://github.com/Charles92011/webrtc-java-experimental-server  
It's a server designed specifically for experimenting with webrtc-java, it has examples of how to save audio and video. You should be able to insert a pot-processing phase to marry the two together.

**Comment by ChdDongyang** [comment]
@Charles92011 Thank you very much, I get it !
