### ISSUE TITLE
how to get MediaStream id?

### ISSUE THREAD

**Issue by zengchuan** [devopvoid/webrtc-java#84]
How to get MediaStream id ? from onTrack(RTCRtpTransceiver transceiver)? or from onAddStream? I can not trigger onAddStream(MediaStream stream).

**Comment by devopvoid** [comment]
Not sure what you mean by `MediaStream id`

Option 1 - the second parameter:
`peerConnection.addTrack(videoTrack, List.of("stream"));`

Option 2 - `transceiver.getMid()` or `track.getId()`
```
for (RTCRtpTransceiver transceiver : peerConnection.getTransceivers()) {
	MediaStreamTrack track = transceiver.getSender().getTrack();

	if (nonNull(track)) {
		// transceiver.getMid() or track.getId()
	}
}
```
