### ISSUE TITLE
Local video is sometimes empty

### ISSUE THREAD

**Issue by vria** [devopvoid/webrtc-java#9]
Hi !

Rarely I get a strange bug that seems to be completely random. In essence, the video of a self camera is empty:

![Screenshot from 2020-12-21 15-10-54](https://user-images.githubusercontent.com/7421651/102787537-854ace80-43a1-11eb-8a98-f29e76c85e20.png)

To reproduce a bug one should simply start a call.

Here are some details:

- this happens once in 30-40 tests,
- a camera lights up,
- a distant peer receives a video form the camera,
- localVideo VideoView appears and sized correctly (a rectangle that is appropriately sized)
- I test mostly on Ubuntu 20 but I've seen this problem on Windows also

Have you ever encountered this bug?

**Comment by devopvoid** [comment]
Hey,
that should be a JavaFX related bug. There is something wrong with the demo view implementation. I guess the frame arrives in the wrong thread. I will correct that.

**Comment by vria** [comment]
Great! It was my suspicion too, I tried to play with threads with no luck.

**Comment by vria** [comment]
I figured out the issue. This is because of clipping in [VideoViewSkin](https://github.com/devopvoid/webrtc-java/blob/9bf8169b2d93c694b14a1529c1968598bf0a440c/webrtc-demo/webrtc-demo-javafx/src/main/java/dev/onvoid/webrtc/demo/javafx/control/skin/VideoViewSkin.java#L156)

```java
Rectangle clip = new Rectangle(newBounds.getWidth(), newBounds.getHeight());
```

Without it everything works well.
