### ISSUE TITLE
How to use Javafx mediaview with this library?

### ISSUE THREAD

**Issue by MCole-K9** [devopvoid/webrtc-java#94]
I'd love to use this library because it wraps webrtc which takes care of my needs. I'm trying to build a Javafx project but i have been kinda lost.  How do i get javafx mediaview to play video from the peerconnection

**Comment by kinsleykajiva** [comment]
you need to review the demo abit

**Comment by MCole-K9** [comment]
> 

i see that it uses a VideoView, but i'm not sure how to get that in my project

i just use this artifact to get webrtc-java in my project, not exactly sure how to get the things from the demo
```
<dependency>
    <groupId>dev.onvoid.webrtc</groupId>
    <artifactId>webrtc-java</artifactId>
    <version>0.6.0</version>
</dependency>
```

I'm new to this whole java space, so bear with me

**Comment by MCole-K9** [comment]
Okay, i found the artifact for the demo
```
 <dependency>
            <groupId>dev.onvoid.webrtc.demo</groupId>
            <artifactId>webrtc-java-demo-javafx</artifactId>
            <version>0.1.0</version>
        </dependency>
```

I'm going to go tinker around and see what happens. Thanks @kinsleykajiva ..  Will close the issue if i get something working

**Comment by kinsleykajiva** [comment]
I have made a demo that uses Janus please review here I hope it will be helpful     https://github.com/kinsleykajiva/javafx-webRTC-desktop-app

**Comment by MCole-K9** [comment]
@kinsleykajiva thank you. i will review as soon as i get a chance

**Comment by devopvoid** [comment]
Closing this here as for questions please use the discussions feature.
