### ISSUE TITLE
Reference for creating macOS Apple Silicon binaries

### ISSUE THREAD

**Issue by doctorpangloss** [devopvoid/webrtc-java#97]
Take a look at https://github.com/Unity-Technologies/com.unity.webrtc/blob/4ea618813de284df567b39dd25dfd2cecc79da79/BuildScripts~/build_libwebrtc_macos.sh#L71

Should be painless to add arm64 early in your webrtc CMakeLists and add the lipo command here: https://github.com/devopvoid/webrtc-java/blob/a92ebc2c5f9cba994f40c80a54f86c0b11709618/webrtc-jni/src/main/cpp/dependencies/webrtc/CMakeLists.txt#L188

**Comment by devopvoid** [comment]
Apple Silicon binary was released for 0.8.0.
